db:
  max_conns:          10
  min_conns:          2
  max_conn_lifetime:  "10m"
  max_conn_idle_time: "5m"
kafka:
  group_id: order-service
  topics:
    OrderCreated:       orders.created
    OrderStatusUpdated: orders.status_updated
    OrderDLQ:           orders.dlq
  worker_pool_size: 10
  batch_size:       50
  batch_timeout:    "10s"
  queue_size:       100
