db:
  max_conns:          10
  min_conns:          2
  max_conn_lifetime:  "10m"
  max_conn_idle_time: "5m"

kafka:
  group_id: order-service
  topics:
    OrderCreated:       orders.created
    OrderStatusUpdated: orders.status_updated
    OrderDLQ:           orders.dlq
