server:
  read_timeout:        "5s"
  read_header_timeout: "3s"
  write_timeout:       "10s"
  idle_timeout:        "60s"
  shutdown_timeout:    "10s"

kafka:
  group_id: order-service
  topics:
    OrderCreated:       orders.created
    OrderStatusUpdated: orders.status_updated
